services:
  db:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo
      MYSQL_USER: test
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_VOLUME_DIR:-./volumes/db_data}/:/var/lib/mysql"

  aws:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volumes/aws_data}:/var/lib/localstack"
